source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

target 'StationFinder' do

  use_frameworks!

  pod 'Masonry', '~> 1.0.2'
  pod 'BPForms', '~> 2.0.2'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'AFNetworking', '~> 3.0'
  pod 'Colours', '~> 5.5.0'
  pod 'BPForms', '~> 2.0.2'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      puts "StationFinder"
    end
  end
  end
